api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: 'swilv'
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
