security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    providers:
        in_memory:
            memory:
                users:
                    apiuser:
                        password: "$2y$13$S7pFH2w.7QmXX3Q4bJm93esGG7i3gn9e2T3jQ1kzFAPcz1wXRNa3C"
                        roles: [ 'ROLE_USER' ]
                    apiadmin:
                        password: "$2y$13$h8HCE7n5qnMqEp76CgAqceju/JPL5Ad8OIXKQEUVecYnk1tO405c."
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        apidoc:
            pattern: "^/api"
            http_basic: true
            provider: in_memory
        main:
            anonymous: true

    access_control:
         - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
